### ISSUE TITLE
Funkciók

### ISSUE THREAD

**Issue by paroczigergo** [lzperx/Phoebe#15]
A feladat kb. 4000 karakteres (kb 1,5 oldal) részletezettségű magyar nyelvű leírása. Nem szerepelhetnek informatikai kifejezések. Lényegében ez az 5. olyan pont, ami u.a. kéri. Hosszadalmas, fájdalmas bullshitelés.

**Comment by danid2** [comment]
karakterek száma szóköz nélkül 1794.... még bullshitelni kell legalább ugyanennyit :S
