### ISSUE TITLE
Projektterv

### ISSUE THREAD

**Issue by paroczigergo** [lzperx/Phoebe#25]
Tartalmaznia kell a projekt végrehajtásának lépéseit, a lépések, eredmények határidejét, az egyes feladatok elvégzéséért felelős személyek nevét és beosztását, a szükséges erőforrásokat, stb. Meg kell adni a csoportmunkát támogató eszközöket, a választott technikákat! Definiálni kell, hogy hogyan történik a dokumentumok és a forráskód megosztása!

**Comment by danid2** [comment]
ezt meg kéne beszélnünk mondjuk szombaton!!
