### ISSUE TITLE
add Oil.class

### ISSUE THREAD

**Issue by paroczigergo** [lzperx/Phoebe#28]

**Comment by danid2** [comment]
először szerintem érdemes lenne az UMLt fixálni pontosan, hogy mi hogyan jöjjön, mielőtt konkrét kódot írunk

**Comment by paroczigergo** [comment]
Módival itt ülünk az E-ben. Igazából csak próbálgatjuk a szinkron kódolást az IntelliJ-vel. Viszont  ezek az osztályok kb így fognak kinénzi, de hát bármikor lehet rajta változtatni.
