### ISSUE TITLE
gombra elfordulás számítása

### ISSUE THREAD

**Issue by Muresan73** [lzperx/Phoebe#31]
hogy keypress vagy számlálóval megoldani hogy 2 ugrás közötti gombnyomás hosszának függvényében változzon az elfordulás nagysága

**Comment by paroczigergo** [comment]
Szerintem ne legyen ez benne, vagyis ne most foglalkozzunk vele. Alapból a sima 1 nyomás =x fokos fordulás is tökéletes.
